# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "openbsd"

  config.vm.network "172.19.1.5"
  config.vm.share_folder("v-root", "/tornado", "../../..", :nfs => true)

  config.vm.provision :shell, :path => "setup.sh"
end
